options:
    formatter: stylish
files:
    include: '**/*.s+(a|c)ss'
rules:
    indentation:
        - 4
        -
            size: 4
    no-css-comments: 0
    nesting-depth: 5
    class-name-format:
        - 1
        -
            convention: camelcase
    mixin-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: camelcase
    property-sort-order:
        - 1
        -
            order: 'smacss'
