language: node_js

cache:
    npm: true
    directories:
        - node_modules

sudo: false

node_js:
    - "lts/*"

before_install:
    - npm install -g lerna jest

install:
    - npm install
    - lerna bootstrap

script: npm test

after_success:
    - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

notifications:
    email: false
