language: node_js

cache:
    npm: true
    directories:
        - node_modules

sudo: false

node_js:
    - "8"

install: npm install

script: npm test

after_success:
    - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

notifications:
    email: false
