language: node_js

node_js:
  - "lts/*"

sudo: false

cache:
    npm: true
    directories:
        - node_modules

branches:
    only:
        - master
        - develop

before_install:
    - npm install -g lerna jest

install:
    - npm install
    - lerna bootstrap --ignore-scripts

script: npm test

after_success:
    - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

notifications:
    email: false
