language: node_js

cache:
    npm: true

sudo: false

node_js:
    - 5
    - 6
    - 7
    - 8

install: npm install

script: npm test

after_success:
    - travis_retry node ./node_modules/.bin/coveralls

notifications:
    email: false
