export { default as definition } from './definition.json';
export { default as api } from './api.json';
export { default as field } from './field.json';
export { default as form } from './form.json';
export { default as layout } from './layout.json';
export { default as list } from './list.json';
export { default as localization } from './localization.json';
export { default as messages } from './messages.json';
// export { default as resource } from './resource.json';
export { default as routes } from './routes.json';
export { default as type } from './type.json';
export { default as lists } from './lists.json';
export { default as forms } from './forms.json';
export * as resources from './resources/index';
